[Feature] Ranking 스크린을 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #102
Opened 2024-10-07 07:39 UTC by librarywon

resolved #92 

## AS-IS
x

## TO-BE
- Ranking Screen을 구현하였습니다.

## KEY-POINT
- 아직 서버로직이 없기 때문에 TODO를 작성해두었습니다.
- Header, body는 그렇게 복잡한 뷰가 아니라고 생각하여 따로 파일을 분리하지 않았습니다.
- PreviewParameter 반영한 프리뷰를 만들어 보았는데 한 번 확인해보시고 의견을 나누었으면 좋겠습니다 ㅎㅎ

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/41e23453-96b3-4a5c-a306-3624b1c48f9c

PreviewParameter 반영버전

<img width="425" alt="스크린샷 2024-10-07 오후 4 38 42" src="https://github.com/user-attachments/assets/264cd52e-c0d3-4ffb-9162-54e2fe6c3b83">

이전에 구현한 preview
<img width="370" alt="스크린샷 2024-10-07 오후 3 32 06" src="https://github.com/user-attachments/assets/27298d9f-ffe4-47f1-bc66-099b16c663b4">

2024-10-15 12:10 UTC, no1msh requested changes
고생하셨습니다! 뷰 잘 구현하셨네요!
코멘트 확인해주세요!

2024-10-15 12:10 UTC, no1msh commented on ranking-presentation/src/main/java/com/teamhy2/ranking/model/RankingUiState.kt
> +)
어차피 서버를 통해 데이터를 가져와야만하는 화면이라면 Loading을 따로 두고
defaultParameter를 제거하는게 어떨까요?

2024-10-15 12:10 UTC, no1msh commented on ranking-presentation/src/main/java/com/teamhy2/ranking/components/RankingItem.kt
> +        )
시퀀스로 만든 다른 이유가 있을까요?

2024-10-15 12:10 UTC, no1msh commented on ranking-domain/src/main/java/com/teamhy2/ranking/model/DepartmentRanking.kt
> +)
도메인 객체라면 `totalStudyTime`이 String 보단 Int가 어울려 보입니다.
심지어 API 명세 상으로도 숫자로 내려옵니다.

이건 추가적인 질문인데 랭킹에 표시되는 시간인 "120H"는 무조건 시간 단위(H)로만 내려오는거 아닌가요?
만약 그렇다면 Int로만 관리해도 좋을 것 같습니다.

2024-10-15 12:11 UTC, no1msh commented
추가로 헤더 부분에 사용된 부등호 모양 아이콘은 제가 가져온걸 사용할 순 없었나요?

2024-10-16 11:59 UTC, librarywon commented on ranking-presentation/src/main/java/com/teamhy2/ranking/model/RankingUiState.kt
> +)
네 좋은생각입니다 반영하겠습니다!

2024-10-16 12:00 UTC, librarywon commented on ranking-presentation/src/main/java/com/teamhy2/ranking/components/RankingItem.kt
> +        )
오 더미를 항상 listOf로 만들어서 시퀀스라는 것을 한 번 써보고 싶었습니다!

2024-10-16 12:02 UTC, librarywon commented on ranking-domain/src/main/java/com/teamhy2/ranking/model/DepartmentRanking.kt
> +)
명세가 제대로 나오지 않은 상태에서 구현한 뷰라서 스웨거를 통해 다시 명세를 확인하고 반영하겠습니다!

2024-10-16 12:06 UTC, librarywon commented
다른 모듈의 이미지리소스를 가져오는게 조심스러운게 있어서 그냥 새로 추가하였습니다

2024-10-23 06:37 UTC, no1msh approved these changes
고생하셨습니다!

2024-10-23 06:47 UTC, merged