[Feature] 바텀네비게이션을 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #111
Opened 2024-10-23 18:25 UTC by librarywon

resolved #89

## AS-IS
Null

## TO-BE
- 바텀네비게이션을 구현하여 화면이동 로직을 구현합니다.
- RankingScreen을 연결합니다.

## KEY-POINT
- 바텀네비게이션이 디자인이 피그마와 다른점이 있습니다. 일단 기능구현이 우선이라고 생각하여 기능 위주로 코드리뷰를 해주시면 감사드리겠습니다.

## SCREENSHOT (Optional)
https://github.com/user-attachments/assets/640ab601-32bb-4526-8843-8fecd35a8a00

2024-10-26 06:59 UTC, no1msh requested changes
코멘트 확인해주세요!

2024-10-26 06:59 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/MainBottomBar.kt
> +    val tabs = listOf(MainTab.HOME, MainTab.RECORD, MainTab.RANKING, MainTab.SETTING)
탭이 늘어나면 수정해줘야합니다. 어떻게 하면 알아서 대응되는 코드를 만들 수 있을까요?

2024-10-26 06:59 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainActivity.kt
> +                    }
하드코딩은 피해주세요!

2024-10-26 06:59 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainActivity.kt
> +                                    }
해당 코드에 대해서 설명부탁드립니다!

2024-10-26 06:59 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainTab.kt
> +            }
from이라는 prefix를 사용하신 이유가 궁금합니다!

2024-10-26 06:59 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainTab.kt
> +) {
`@DrawableRes` 어노테이션을 추가해주세요.

2024-10-27 06:20 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/MainBottomBar.kt
> +    val tabs = listOf(MainTab.HOME, MainTab.RECORD, MainTab.RANKING, MainTab.SETTING)
MainTab 제가 만들어둔 enum class를 사용하면 될 것 같습니다.

`val tabs = enumValues<MainTab>().toList() ` 이렇게 변경하겠습니다.

2024-10-27 06:34 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainTab.kt
> +            }
Route String를 통해서 MainTab 객체를 반환하는 의미로 from이라는 단어를 사용하였습니다.

2024-10-27 06:37 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainActivity.kt
> +                                    }
```
 popUpTo(navController.graph.startDestinationId) {
                                            saveState = true
                                        }
```
부분은  사용자가 다른 탭을 선택했을 때 이전의 화면들이 남아 있지 않도록 백 스택을 정리하고 ` saveState = true`를 사용하여 현재 상태를 저장합니다.

`launchSingleTop = true` 는 동일한 화면이 여러번 생기는 것을 방지합니다 홈을 다다닥 눌러도 홈이 여러번 쌓이지 않는 것을 볼 수 있습니다.

`restoreState = true`는 상위에  `saveState = true` 속성을 통해서 저장해둔 상태를 복원하는 역할을 수행합니다.

2024-10-27 07:48 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/MainBottomBar.kt
> +    val tabs = listOf(MainTab.HOME, MainTab.RECORD, MainTab.RANKING, MainTab.SETTING)
저는 `val tabs = MainTab.entries.map ...` 생각하긴 했는데 명시하신 코드와 차이가 뭘까요?!

2024-10-27 08:00 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/MainBottomBar.kt
> +    val tabs = listOf(MainTab.HOME, MainTab.RECORD, MainTab.RANKING, MainTab.SETTING)
차이가 없는 것 같습니다 entries 가 제가 알기로는 최신 코틀린 버전에 적합한 형태로 알고 있습니다.

2024-10-27 08:02 UTC, no1msh requested changes
고생하셨습니다! 마지막으로 몇개만 고쳐보죠!

2024-10-27 08:02 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainActivity.kt
> +                                    }
코드 이해 완료하였습니다.
그렇다면 랭킹과 같은 화면은 사용자가 탭을 누를 때 데이터가 갱신을 원할 가능성이 높기 떄문에, 조치가 필요해 보입니다!

2024-10-27 08:02 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainTab.kt
> +            }
[자바 공식문서 기준 팩토리 메서드 네이밍 컨벤션](https://siahn95.tistory.com/176) 이런 것도 있습니다.
잘 사용하신 거 같아요!

2024-10-27 08:06 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/MainActivity.kt
> +                                    }
상태저장과 불러오는 속성을 제거함으로 조치를 하겠습니다!

2024-10-27 09:59 UTC, no1msh approved these changes
고생하셨습니다!

2024-10-27 13:27 UTC, merged