구글 로그인 및 회원관련 서버연결
Woosopt/HongikYeolgong2-Android pull request #112
Opened 2024-10-25 05:52 UTC by no1msh

resolved #101 

## AS-IS
FirebaseAuth 기반의 구글로그인에서

## TO-BE
GoogleCloudPlatform OAuth2 + CredentialManager를 활용하는 방법으로 변경합니다.

## KEY-POINT
- 서버 기반작업도 같이 하느라 조금 PR 규모가 큰점 죄송합니다!
- 구글 로그인을 재구현 하면서 여러가지 회원관련 서버 연결 및 기반 작업도 같이 하게 되었습니다.
- 현재 android sdk34(갤럭시 z플립6, 갤럭시 s24수준) 이상만 정상적으로 로그인이 진행되는 현상을 파악하였습니다.
- 자동로그인도 미구현 상태라 따로 구현하여 PR 올리도록 하겠습니다!

### Retrofit Qualifier
토큰이 헤더에 담겨야 하는 요청을 담당하는 레트로핏 객체와 토큰이 필요없는 요청을 담당하는 레트로핏 객체를 따로 사용하기 위해
다음과 같이 hilt의 Qualifier annotation을 사용하였습니다.
![image](https://github.com/user-attachments/assets/b03138f3-63d1-4e40-bfa6-5aa0a35af76b)

### 궁금하신 점 있으시면 질문 주세요!

## SCREENSHOT (Optional)
![Oct-25-2024 14-45-37](https://github.com/user-attachments/assets/4da6e78d-e8de-4524-88dc-9bbc90aebd68)

2024-10-25 09:34 UTC, librarywon requested changes
구글 로그인과 사투하시느라 너무 고생 많으셨습니다!!!!!! 
최대한 코드를 이해하고 플로우를 이해하려고 노력하였고 제안수준의 리뷰가 있으니 확인해주시면 감사드리겠습니다!

2024-10-25 09:34 UTC, librarywon commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignIn.kt
> +        }
이 로직은 공식문서 있는걸까요?  SHA-256 알고리즘을 이용한 해시 난수 생성 처음 보아서요!

2024-10-25 09:34 UTC, librarywon commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignInButton.kt
> +        colors = ButtonDefaults.buttonColors().copy(containerColor = White),
웹소소컬러에도 White가 있을 것 같습니다!

2024-10-25 09:34 UTC, librarywon commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignInButton.kt
> +) {
드디어 디자이너가 원하는 디자인으로 가능하게 되었군요!

2024-10-25 09:34 UTC, librarywon commented on core/remote/src/main/java/com/benenfeldt/remote/di/NetworkModule.kt
> +            .build()
` Qualifier annotation`에 대해서 처음 알았고 너무 유용한 어노테이션이네요 배우고 갑니다 👍

2024-10-25 09:34 UTC, librarywon commented on core/remote/src/main/java/com/benenfeldt/remote/dto/DefaultResponse.kt
> +data class DefaultResponse<T>(
`BaseResponse` 어떠신가요 제안드립니다!

2024-10-25 09:34 UTC, librarywon commented on core/remote/src/main/java/com/benenfeldt/remote/dto/UserNicknameDuplicationResponse.kt
> +)
`nickname` 을 Response로 내려줄 필요가 없어 보이는데 서버에서 내려주시네요 중복 여부만 알려주면 되는거 아닌가 생각이듭니다!

2024-10-25 09:34 UTC, librarywon commented on core/remote/src/main/java/com/benenfeldt/remote/mapper/ResultMapper.kt
> +}
잘 사용하겠습니다!

2024-10-25 09:34 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/HY2NavHost.kt
> +                    navController.popUpToOnboarding()
감사합니다!

2024-10-25 09:34 UTC, librarywon commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    onGuestSignedIn: () -> Unit,
```suggestion
    onPublicUserSignedIn: () -> Unit,
```
아직 가입하지 않은 유저를 일관성 있게 `PublicUser`로 네이밍을 변경하는 것은 어떤가요

2024-10-25 09:34 UTC, librarywon commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    onGuestSignedIn: () -> Unit,
Guest도 사실 좋습니다! 비로그인으로 서비스를 이용할 수 있는 서비스의 느낌이 나서 제안해보았습니다!

2024-10-25 09:34 UTC, librarywon commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    }
when을 사용하시지 않은 이유는 else를 피하고 싶으신 이유가 크겠죠?!

2024-10-25 09:34 UTC, librarywon commented on core/remote/src/main/java/com/benenfeldt/remote/dto/UserNicknameDuplicationResponse.kt
> +)
해결되었습니다.

2024-10-25 13:40 UTC, no1msh commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignIn.kt
> +        }
공식문서에선 못봤고 CredentialManager를 다루는 [영상](https://www.youtube.com/watch?v=P_jZMDmodG4)에서 참고하였습니다!

2024-10-25 13:42 UTC, no1msh commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignInButton.kt
> +        colors = ButtonDefaults.buttonColors().copy(containerColor = White),
웹소소 컬러에 있는진 모르겠고..ㅎㅎ White색상은 디자인 시스템에 유일하게 존재하는 것을 가져왔습니다.
실제 디자인에서도 `#FFFFFF`입니다!

2024-10-25 13:46 UTC, no1msh commented on core/remote/src/main/java/com/benenfeldt/remote/mapper/ResultMapper.kt
> +}
주로 서비스객체가 반환하는 Response DTO를 들고 있는 `Result<xxxResponse>` 를 도메인 객체로 변경시켜 Repository가 반환할 수 있게 `Result<xxx>`로 바꿔주는 용도로 사용합니다.
사용하실 때 어려우시면 다시 질문 주세요!

2024-10-25 13:51 UTC, no1msh commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    }
지금은 임시적인 코드라고 보셔도 좋을 것 같습니다. 추후 errorFlow 연결시 변경될 가능성이 높습니다.

2024-10-25 14:04 UTC, no1msh commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    onGuestSignedIn: () -> Unit,
사실 가입을 하고 로그인을 하는 플로우가 일반적인데ㅠ
정반대라 네이밍을 하는 것도 조금 어렵게 느껴지는 군요ㅠ
지금은 게스트가 그나마 잘어울리는 거 같아요. 로그인은 했지만, 고객은 아닌...
일단은 현행 유지하고 추후, 게스트 로그인을 저희가 구현한다면 그때 다시 네이밍 변경을 고려해보겠습니다!

2024-10-27 05:57 UTC, librarywon commented on core/auth/src/main/java/com/teamhy2/core/auth/GoogleSignInButton.kt
> +        colors = ButtonDefaults.buttonColors().copy(containerColor = White),
와 근데 깃허브에 이런 기능도 제공해주네요 ㅋㅋㅋ
<img width="110" alt="스크린샷 2024-10-27 오후 2 57 23" src="https://github.com/user-attachments/assets/fac2e8db-bc75-4a0a-a24c-b61c9d90b09c">

2024-10-27 05:58 UTC, librarywon commented on onboarding-presentation/src/main/java/com/teamhy2/onboarding/OnboardingScreen.kt
> +    onGuestSignedIn: () -> Unit,
네 말씀해주신 내용 이해하였고 확인하였습니다!

2024-10-27 05:59 UTC, librarywon approved these changes
모든 리뷰를 확인하였습니다 고생하셨습니다!

2024-10-27 07:45 UTC, merged