[Feature] RecordScreen UI를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #114
Opened 2024-10-25 11:17 UTC by librarywon

resolved #109 

## AS-IS
- 기존 Main에 있는 캘린더를

## TO-BE
- RecordScreen으로 이전하고 공부시간을 표시하는 컴포넌트를 추가합니다.

## KEY-POINT
- 데이터로직을 제외하고 구현하였기 때문에 실제 화면을 눌러보면 loading indicator만 보이는 상황입니다. 프리뷰를 봐주시면 UI 파악이 가능합니다.
- 지금 열려있는 BottomeNavigation에서 브랜치를 파서 작업을 했기 때문에 #111 머지 이후에 확인해주시면 됩니다!

## SCREENSHOT (Optional)
<img width="263" alt="스크린샷 2024-10-25 오후 8 14 50" src="https://github.com/user-attachments/assets/a9e50943-febd-402e-87eb-a052f0517b19">

2024-10-26 07:09 UTC, no1msh requested changes
고생하셨습니다! 알아서 바텀네브 내용 제외한체로 리뷰하였습니다.

<img width="735" alt="image" src="https://github.com/user-attachments/assets/89eaad2c-63cb-40a1-a220-23e241d9d65b">
다음부턴 위 사진 처럼 구현한 커밋만 필터링 한뒤 url을 넘겨주시면 좀 더 쉽게 작업한 내용을 확인할 수 있게 해주세요!

2024-10-26 07:09 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +            }
꽤 자주 사용되는 컴포넌트인거 같은데 공컴으로 빼도 좋을 것 같습니다.

2024-10-26 07:09 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +            get() = _recordUiState.asStateFlow()
커스텀 getter를 사용하신 이유는 무엇인가요?

2024-10-27 05:55 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +            }
확인하였습니다 `HY2CirularLoading` 정도로 이름을 정하면 좋을까요?

2024-10-27 05:55 UTC, librarywon commented
커밋모아서 볼 수 있는 기능이 있다는 것을 깜빡했었네요!

2024-10-27 06:09 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +            get() = _recordUiState.asStateFlow()
사실 관성적으로 사용한 것이 크고 캡슐화 이외에는 큰 의미를 두지 않았던 것 같습니다!

2024-10-27 08:03 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +            }
넵 충분해보이고 다른 Loading 형태가 없고, 만약 화면 전체를 덮는다면 `HY2LoadingScreen` 해도 될 것 같네요.

2024-10-27 08:25 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +            get() = _recordUiState.asStateFlow()
지금 코드는 커스텀 게터를 사용하지 않으셔도 됩니다!
다른 뷰모델들 처럼 바꿔주세요!

2024-10-27 08:41 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +            get() = _recordUiState.asStateFlow()
넵 확인하였습니다!

2024-10-27 10:06 UTC, no1msh commented
@librarywon `LoadingScreen` 파일명만 변경하셨습니다!

2024-10-27 10:06 UTC, no1msh approved these changes

2024-10-28 04:26 UTC, merged