[Feature] RecordScreen data 로직을 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #128
Opened 2024-11-05 13:50 UTC by librarywon

resolved #123 

## AS-IS
- RecordScreen에 data로직이 구현되어 있지 않았습니다.

## TO-BE
- RecordScreen에 연간, 월간 등 공부 기록과 캘린더에 공부기록을 가져옵니다.
- 기존 Main에 존재하는 캘린더 컴포넌트의 기능들을 마이그레이션합니다.

## KEY-POINT
### 캘린더 데이터를 가져오는 로직
- 현재 api 상으로는 모든 공부 이력을 보내주는 구조입니다. 그러므로 모든 기록을 최초 한 번 가져와 원하는 달의 값만 보내주는 구조로 코드를 작성하였습니다.
```
      private val cachedStudyDays: MutableMap<YearMonth, List<StudyDay>> = mutableMapOf()
        private val cacheMutex: Mutex = Mutex()

        override suspend fun updateCalendarStudyDay(): Result<Unit> {
            return studyService.getCalendarStudyDay().map { response ->
                val studyDays: List<StudyDay> = response.data.map { it.toDomain() }
                cacheMutex.withLock {
                    cachedStudyDays.clear()
                    studyDays.forEach { studyDay ->
                        val yearMonth: YearMonth = YearMonth.from(studyDay.date)
                        cachedStudyDays[yearMonth] =
                            cachedStudyDays.getOrDefault(yearMonth, emptyList()) + studyDay
                    }
                }
            }
        }

        override suspend fun fetchStudyDaysForYearMonth(date: LocalDate): List<StudyDay> {
            val yearMonth: YearMonth = YearMonth.of(date.year, date.month)
            return cacheMutex.withLock {
                cachedStudyDays[yearMonth] ?: emptyList()
            }
        }
```

코드를 설명드리자면 `updateCalendarStudyDay()`를 통해서 모든 공부 이력들을 가져와 캐싱을하게됩니다. 

캐싱된 데이터도 일종의 디비의 역할을 하기 때문에 무결성이 중요하고 그래서 캐싱을 하는 과정에 Mutex의 lock을 이용하였습니다.

lock을 이용하면 트렌젝션 역할을 하는 `withLock{} `내부 코드가 작동할 때 다른 코드가 작동하지 않게 만들어서 일관성을 보장할 수 있습니다.
(운영체제 때 배운 지식이 여기서 나오니까 재밌네요)

실제로 뷰모델은 `fetchStudyDaysForYearMonth(date: LocalDate)`를 통해서 캐싱된 데이터를 받게 됩니다. `date`가 `LocalDate`타입인건 캘린더의 date 타입과 동일하게 맞추기 위함입니다.

### RecordViewModel이 최초로 데이터를 불러오는 로직
```
  viewModelScope.launch {
                runCatching {
                    val results =
                        listOf(
                            async { studyDurationRepository.fetchStudyDuration().getOrThrow() },
                            async { calendarStudyDayRepository.updateCalendarStudyDay().getOrThrow() },
                        ).awaitAll()

                    val now: LocalDate = LocalDate.now()
                    val calendarStudyDays: List<StudyDay> =
                        async { calendarStudyDayRepository.fetchStudyDaysForYearMonth(now) }.await()

                    _recordUiState.update {
                        RecordUiState.Success(
                            studyDuration = results[0] as StudyDuration,
                            calendar = Calendar(studyDays = calendarStudyDays),
                        )
                    }

```

실제로 원하는 달의 공부이력을 가져오는 `fetchStudyDaysForYearMonth()`함수는 **무조건** 캐싱을 하는 `updateCalendarStudyDay()`가 선행되고 실행되어야하는 함수입니다. 

그래서 먼저 함수를 실행시키고 `awaitAll()`을 통해 끝을 보장 받은 뒤에  `fetchStudyDaysForYearMonth()`가 실행되도록 구조를 작성하였습니다. 

혹시 `fetchStudyDaysForYearMonth()`이 끝나지 않고 UiState를 update하는 불상사를 막기위해 await()도 추가해주었습니다.

* 지금 생각이 났는데 앱을 킨 후에 공부한 내역이 반영될려면 다시 한 번 서버통신을 진행해야하는데 이 로직은 어떻게 구상하는게 좋을까요?

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/a955095d-367c-41c1-a693-2b0769a36025

2024-11-06 05:12 UTC, no1msh requested changes
로직 복잡하셨을텐데 고생 많으셨습니다!
일단 모두 본건 아니고, 리뷰 반영에 집중할 수 있게 뷰모델 쪽 위주로 봤습니다.

`RemoteCalendarStudyDayRepository`은 다음 리뷰 때 확인하겠습니다!

화이팅!

2024-11-06 05:12 UTC, no1msh commented on record-data/src/main/java/com/teamhy2/record/data/mapper/StudyDayMapper.kt
> +}
이 파일에서만 사용된다면 private, 이 파일이 포함된 모듈에서만 사용된다면 internal을 붙여주세요.
안그러면 해당 모듈을 참조하고 있는 모든 모듈에서 `1.toStudyRoomUsage()`가 가능합니다.

2024-11-06 05:12 UTC, no1msh commented on record-data/src/main/java/com/teamhy2/record/data/di/RecordModule.kt
> +}
구현체 파라미터 네임을 `remoteStudyDurationRepository`로 바꿔주세요.
지금은 `imp`입니다.

2024-11-06 05:12 UTC, no1msh commented on record-domain/src/main/java/com/teamhy2/record/domain/repository/StudyDurationRepository.kt
> +}
get이라는 접두사로 통일합시다!

2024-11-06 05:12 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                }
`emit`과 `tryEmit`의 차이는 무엇인가요?

2024-11-06 05:12 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                }
> 실제로 원하는 달의 공부이력을 가져오는 fetchStudyDaysForYearMonth()함수는 무조건 캐싱을 하는 updateCalendarStudyDay()가 선행되고 실행되어야하는 함수입니다.

선행된다는게 아마 `updateCalendarStudyDay()`가 완료되고 나서 `fetchStudyDaysForYearMonth()`이 실행이 되어야 하는 거같은데, 사실상 async를 사용함으로써 병렬로 처리되어 전혀 반대되는 상황으로 연출이 되는 것 같습니다.

2024-11-06 05:12 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                        async { calendarStudyDayRepository.fetchStudyDaysForYearMonth(now) }.await()
now는 한 군데에서 만 사용되고 코드 길이가 길지 않기에 이 정도는 inline 해도 될 것 같습니다.

2024-11-06 05:12 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                        async { calendarStudyDayRepository.fetchStudyDaysForYearMonth(now) }.await()
또한 async 블록 바로 뒤에 .await()을 사용하는 것은 의미가 없는 코드입니다.

> 참고: 코틀린 코루틴 딥다이브 30장 모범사례

어차피 viewmodelScope.launch 빌더에서 suspend fun을 통해 값을 가져오는 거라면
`val calendarStudyDays: List<StudyDay> = calendarStudyDayRepository.fetchStudyDaysForYearMonth(now)`
이렇게도 가능하지 않나요?

2024-11-06 05:12 UTC, no1msh commented on record-domain/src/main/java/com/teamhy2/record/domain/repository/CalendarStudyDayRepository.kt
> +}
다른것들 처럼 Result로 래핑하지 않은 이유가 뭔가요?
사용하는 쪽에서는 runCatching으로 래핑해서 사용하는 모습을 본것 같은데, 그렇다면 애초에 반환할 때 Result로 래핑해서 반환하는게 나아보입니다.

제가 생각하지 못하는 이유가 있을 수 있다면 알려주세요!

2024-11-06 05:12 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                        }
update 사용 👍

2024-11-06 05:59 UTC, librarywon commented on record-data/src/main/java/com/teamhy2/record/data/di/RecordModule.kt
> +}
다른 곳에 구현하신 곳을 보고 일관성 있게 맞췄다고 생각했는데 그건 디폴트 프리픽스를 쓸 때였네요 수정하겠습니다.

2024-11-06 05:59 UTC, librarywon commented on record-data/src/main/java/com/teamhy2/record/data/mapper/StudyDayMapper.kt
> +}
이 모듈 혹은 이 모듈을 참조하는 모듈 전체에 Int에 확장함수를 만들어버린 꼴이군요 확인하였습니다.

2024-11-06 06:03 UTC, librarywon commented on record-domain/src/main/java/com/teamhy2/record/domain/repository/StudyDurationRepository.kt
> +}
서비스함수 -> 서버 메서드 관련 함수 사용 (get, post, put)
이외에 함수 -> 서버 의존적이지 않은 네이밍 사용 (fetch, save, update)
이렇게 일종의 규칙을 가지고 사용하고 있는데 어떠신가요?

2024-11-06 06:14 UTC, librarywon commented on record-domain/src/main/java/com/teamhy2/record/domain/repository/CalendarStudyDayRepository.kt
> +}
서버통신에 관련한 친구가 아니라고 생각해서 래핑을 따로 진행하지 않았었는데 그건 사실 크게 상관이 없었던 문제 같네요 일관성 있게 Result<>로 진행하겠습니다!

2024-11-06 06:21 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                }
아 코루틴에 대해서 완전히 헷갈리고 있었던거 같습니다. async로 두개를 돌리고 waitAll을 하면 그 뒤에 코드가 안넘어간다고 생각을 하고 있었군요.. 코루틴에 대해서 다시 점검이 필요한거 같습니다.

2024-11-06 06:21 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                        async { calendarStudyDayRepository.fetchStudyDaysForYearMonth(now) }.await()
now를 인라인시키고 말씀해주신 방식으로 calendarStudyDays도 가능합니다 위에 리뷰를 같이 반영해서 해결 해보겠습니다.

2024-11-06 06:31 UTC, librarywon commented on record-data/src/main/java/com/teamhy2/record/data/di/RecordModule.kt
> +}
main도 그렇게 한 것 같아서 같이 수정하겠습니다.

2024-11-06 06:36 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordViewModel.kt
> +                }
`tryEmit`은 StateFlow가 수신할 준비가 될 때까지 기다리지 않고 즉시 데이터를 발행하려고 시도합니다. 구독자가 준비가 안되도 발행하니 무조건 이벤트를 수신하지 않아도 될 때 사용한다고 합니다. `emit()`이 저희가 예상하는 기능이 맞으니 수정하겠습니다.

. 을 찍어서 나오는 `tryEmit()`을 그냥 사용한 것 같습니다. 이번 기회에 공부를 같이 하게 됬네요 ㅋㅋㅋㅋㅋ

2024-11-06 09:16 UTC, no1msh commented on record-domain/src/main/java/com/teamhy2/record/domain/repository/StudyDurationRepository.kt
> +}
저는 오히려 서버 관련 함수 네이밍이 (fetch, save, update) 느낌나네요.

> git fetch vs git get

레포지토리 함수는 최대한 로컬과 서버 등 어떤 데이터 소스를 쓰느냐 상관없이, 모든 걸 아우르는 네이밍이어야 한다 생각해서 해본 말이었습니다!

2024-11-08 06:45 UTC, no1msh requested changes
하나만 확인하시고 다시 요청 주시면 어프루브 누르겠습니다!

2024-11-08 06:45 UTC, no1msh commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +    }
이렇게 처리하면 lifecycle이 변경될때마다 다시 등록하는 형태 같아보입니다.
등록은 한번만 해도 된다면 `LaunchedEffect(Unit)` 해도 될 것 같은데 해보셨을까요?

2024-11-08 06:49 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +    }
지금 시도해보겠습니다!

2024-11-08 06:59 UTC, librarywon commented on record-presentation/src/main/java/com/teamhy2/record/RecordScreen.kt
> +    }
`Unit` 변경해도 문제 없음을 확인하였습니다 수정하여 커밋하겠습니다.

2024-11-08 07:04 UTC, no1msh approved these changes
고생하셨습니다!

2024-11-08 07:24 UTC, merged