[Fix] 타이머가 doze 모드에서 멈추는 현상 해결
Woosopt/HongikYeolgong2-Android pull request #135
Opened 2024-11-15 20:17 UTC by librarywon

resolved #132 

## AS-IS
- 안드로이드 휴대폰은 화면을 잠구고 일정 시간이 지나면 doze 모드에 들어가게 됩니다. 이 때 타이머가 작동하지 않아 사용자에게 알람을 보내지 않는 문제가 발생하였습니다.

## TO-BE
- ForegroundService를 이용하여 앱을 나가더라도 종료되지 않았다면 시간을 체크하여 알람을 보내는 TimerForegroundService를 구현하여 반영하였습니다.

## KEY-POINT
- 저도 처음 해보는 기능이라 최대한 자세히 설명을 해보겠습니다. 
- 기존의 타이머와 연동하면 좋았겠지만 일단 기능 구현에 집중하였으며 직접 브랜치를 체크아웃하여 프로젝트를 돌려보시는 것을 추천드리겠습니다!

### NotificationHandler에서 ServiceNotification 빌더를 따로 만들어준 이유
- 일반적으로 30분, 10분, 종료 알람을 주는 경우에는 사용자가 쉽게 제거할 수 있고 알아서 제거되는 `setAutoCancel(true)` 등의 속성을 사용합니다.
- 그에 비해 서비스용 알람은 제거되지 않도록 `setOngoing(true)` 속성을 활성화 해야 하며 알람 아이콘의 내용도 다르기 때문에 분리하여 빌더를 추가하였습니다.

### TimerForegroundService 대한 설명
- 기존의 타이머와 남은시간을 처리하는 로직(남은시간 = 끝나는 시간 - 현재시간)은 동일합니다.

- 동반 객체의 `startService()`, `stopService()` 를 통해서 타이머의 시작과 종료를 조절합니다. 서비스에 원하는 값을 전달하고 싶다면 Intent에 포함시켜 전달하는 방식을 사용해야 값이 전달 가능합니다.

- `onStartCommand()` 메서드는 서비스가 시작될 때 호출되며, 타이머 시작 시간을 Intent로 전달받아 처리합니다. 그리고 startTimer 메서드를 호출하여 타이머를 실행한 뒤에 알림을 생성하고 표시합니다.

- 내부 `startTimer()` 함수는 혹시 내부 타이머가 돌고 있다면 종료시키고 1초(1000L)마다 남은시간을 계산하여 특정 시간마다 알람을 발송합니다.

## SCREENSHOT (Optional)

2024-11-16 14:11 UTC, no1msh requested changes
고생하셨습니다! 조금만 더 힘을내주세요!

2024-11-16 14:11 UTC, no1msh commented on app/src/main/AndroidManifest.xml
> +            android:foregroundServiceType="dataSync"/>
`dataSync` 처리를 해주면 어떻게 되나요?

2024-11-16 14:11 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +        }
인자로 context를 받고 있는데, ApplicationContext를 넣는것과 ActivityContext를 넣는것의 차이는 없을까요?

2024-11-16 14:11 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +    private val serviceScope: CoroutineScope = CoroutineScope(Dispatchers.Main)
MainThread에서의 동작이 필수적인가요?

2024-11-16 14:11 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                    }
역순으로 비교하고 if문안에 `continue`를 사용하면 `hasNotified~` 상태 변수가 필요없지 않나요?

2024-11-16 14:11 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeScreen.kt
>              ),
필요없다면 Timer 객체에서 이벤트를 끝날때만 받아도 되지않을까요?

또한 지금 보니 `TIME_OVER_SECONDS`는 좀 어색한 변수명 같네요!

2024-11-17 06:44 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +            android:foregroundServiceType="dataSync"/>
foregroundServiceType는 여러가지 타입이 있는데 반드시 포그라운드 서비스에 맞는 타입을 설정해주어야합니다.
`dataSync`가 저희가 원하는 목적과 가장 비슷하여 설정하였습니다. 없으면 터집니다.

![image](https://github.com/user-attachments/assets/5f4fc9b8-031e-44bd-bdd4-7f61a4907ded)

https://developer.android.com/develop/background-work/services/fg-service-types?hl=ko

2024-11-17 07:01 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +        }
돌아가는 것은 문제가 없어보이는데 포그라운드서비스 목적을 생각해보면 `ApplicationContext`를 사용하는 것이 좋을 것 같습니다 항상 어플리케이션 컨텍스트를 사용하도록 수정하겠습니다.

2024-11-17 07:01 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +    private val serviceScope: CoroutineScope = CoroutineScope(Dispatchers.Main)
필수적입니다 아니면 터지더라구요

2024-11-17 07:06 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                    }
맞습니다 0초면 break까지 해도 괜찮을꺼 같네요!

2024-11-17 07:07 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeScreen.kt
>              ),
넵 맞습니다 수정하겠습니다

2024-11-17 14:36 UTC, no1msh approved these changes
고생하셨습니다!

2024-11-19 03:40 UTC, merged