[Feature] HY2Button 공통 컴포넌트를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #14
Opened 2024-07-16 08:31 UTC by librarywon

resolved #10 

## AS-IS
재사용 가능성이 높아보이는 텍스트가 포함된 버튼을

## TO-BE
디자인 시스템에 구현합니다.

## KEY-POINT
- 디자인적 통일성을 위해 `Modifer`를 받지 않았는데 가로길이나 높이를 다르게 하는 확장성을 위해 받아야할지 고민입니다.
- switch PR에서 언급하셨던 것과 같은 이유로 크기관련 dp는 상수화하지 않았습니다.
- `ROUNDED_CORNER_SIZE`는 clip에서도 사용하고 디자인이 바뀌어도 크게 변경되지 않을 것 같아 상수화하였습니다.
- 버튼 눌림 효과는 기본 컴포넌트 그대로 사용하였습니다.

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/7abcb9f4-015d-44da-b0b4-0b8082f101b5

2024-07-16 13:38 UTC, no1msh requested changes
고생하셨습니다!
몇 가지 코멘트 달아놨으니 확인 후 반영해주세요!

2024-07-16 13:38 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +    onClick: () -> Unit,
`modifier` 파라미터를 제공하는 것이 맞아보입니다.

버튼의 경우 weight를 줄 수도 있고, 여러가지 크기 관련 값을 줄 수 있는게 좀 더 보편적인 구현같습니다!

2024-07-16 13:38 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +                .clip(RoundedCornerShape(ROUNDED_CORNER_SIZE.dp)),
- 해당 `modifier`에 주어지는 패딩은 왜 상수화 하지 않으셨나요??
- 또한 이 패딩은 사용하는 입장에서 예상치 못한 패딩 값이 될 수 있을 것 같아 보입니다.
- 이것도 `clip`을 사용하지 않으면 리플 효과가 각지게 나오는 현상이 있나요?

2024-07-16 13:38 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +}
접근제어자를 설정해줘도 좋을 것 같네요!

2024-07-16 13:46 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +    onClick: () -> Unit,
아 역시 고민을 많이 했었는데 파라미터 제공하는 것이 좋을 것 같군요 의견 감사합니다.

2024-07-16 14:26 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +                .clip(RoundedCornerShape(ROUNDED_CORNER_SIZE.dp)),
1. 디자인이 달라져 높이가 달라지면 패딩도 수정되어야 할 것 같아 패딩은 상수화하지 않았습니다.
2. `패딩은 사용하는 입장에서 예상치 못한 패딩 값`에 대해서 다시 설명해주실 수 있으실까요?
3.  당연히 각질 것 같아서 적어주었는데 button 컴포넌트는 클립 처리가 되어 있는 것 같습니다 제거 하겠습니다.

2024-07-16 14:52 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +                .clip(RoundedCornerShape(ROUNDED_CORNER_SIZE.dp)),
2. 지금은 컴포넌트에 자체적으로 패딩이 있는 상황이라 사용하는 입장에서 8dp를 고려한체 원하는 디자인을 구현해야합니다.

예를들어, 100dp width를 가진 박스안에 해당 컴포넌트를 넣으면 양옆으로 8dp가 띄어진 상태라 총 84dp width를 가진 버튼이 될 것입니다.

2024-07-17 08:37 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Button.kt
> +                .clip(RoundedCornerShape(ROUNDED_CORNER_SIZE.dp)),
그렇게 될 수 있겠군요! 패딩 값을 제거하고 기본 height 값을 제공하겠습니다!

2024-07-19 12:17 UTC, no1msh approved these changes
고생하셨습니다!

2024-07-19 15:13 UTC, merged