[Fix] 자정 기준으로 발생할 수 있는 시간 버그들을 수정
Woosopt/HongikYeolgong2-Android pull request #149
Opened 2024-12-01 08:00 UTC by librarywon

resolved #147 
resolved #148 

## AS-IS
- 자정이 지나서 열람실 이용을 종료한다면 시작날짜가 종료날짜와 동일하게 나오는 현상 발생
- `12월 4일 오전 1시`에 `12월 3일 오후 23시 50분`을 고르면 `12월 4일 오후 23시 50분`이 선택되는 현상 발생

## TO-BE
- 열람실 이용 종료시 저장해둔 시작날짜를 불러오는 로직으로 수정하여 시작날짜가 올바르게 전송됩니다.
- `HY2TimePicker`가 어제 날짜인지 판단하여 날짜를 보정합니다.

## KEY-POINT
- `startTime`변수가 `LocalDateTime`자료형인데 Time이라는 이름만 사용하는 것은 적절하지 않다고 생각하여 변수 이름을 변경하였습니다.
- `parseStartTimeToLocalDateTime`라는 함수는 `HY2TimePicker`가 앞의 함수 기능을 수행하기 때문에 제거하였습니다.

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/bebb2817-57fb-461c-8788-ad0dc37c256e

2024-12-01 14:54 UTC, no1msh requested changes
고생하셨습니다. 코멘트 확인해주세요!

2024-12-01 14:54 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2TimePicker.kt
> +                            }
코드가 이해가 가지 않는데 자세한 설명 가능하실까요?

2024-12-01 14:54 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/TimerUiModel.kt
>      val endTime: String = "",
UiModel 이라는 표현을 굳이 쓰지 않아도 될 것 같습니다.

UiModel -> Ui에 표시하려고 만드는 모델 -> UiState로 충분히 대처가 가능하다고 생각합니다.

`TimerUiState`로 변경해주세요!

2024-12-01 14:54 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeViewModel.kt
>                  }
`saveStudyDay`에 인자로 들어가는 `parameterName`을 붙여주세요!

- 코틀린 다운 코드
- github에서 봐도 이해하기 좋은 코드

2024-12-02 01:27 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2TimePicker.kt
> +                            }
절대값을 사용해서 헷갈릴 수 있었던 것 같습니다

예를 들어 `12월 2일 오전 1시`에 `12월 1일 오후 11시`를 선택한다면 기존 로직으로는  `12월 2일 오후 11시`가 선택되어 보정이 필요합니다. 

그러므로 보정에는 기준이 필요한데요. 그 기준을 선택된DateTime 과 현재DateTime 절대값 차이가 `MAXIMUM_PREVIOUS_TIME`보다 크면 이전 날짜를 선택했다고 간주하고 값을 보정하는 것 입니다.

위의 예시를 기준으로 한다면  `12월 2일 오전 1시`과 `12월 2일 오후 11시` 차이는 `22시` 이므로 이전 날짜라 보정을 해줍니다.

2024-12-02 01:28 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/TimerUiModel.kt
>      val endTime: String = "",
너도 이질감을 느끼고 있었는데 좋은 피드백 감사합니다.

2024-12-02 01:38 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2TimePicker.kt
> +                            }
절대값을 사용하지 않고 `현재시간 - 선택한 시간`을 그냥 사용해도 가능은 하지만 

절대값을 사용한 이유는 현재 저희 로직상 현재시간보다 미래 시간을 고를 가능성도 존재하고 -값 처리가 문제가 생길 우려가 있어 보였습니다.

2024-12-02 06:39 UTC, no1msh approved these changes
고생하셨습니다.

2024-12-02 07:05 UTC, merged