[Feature] PromtionDialog를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #153
Opened 2024-12-06 08:36 UTC by librarywon

resolved #152 

## AS-IS
null

## TO-BE
- Promotion 팝업을 구현합니다.
- RemoteConfig를 통해 데이터를 가져오며 dataStore를 이용하여 "오늘 보지 않기" 기능도 구현합니다.

## KEY-POINT

### 최종 프로모션 기능 구현
![updated_promotion_architecture_diagram](https://github.com/user-attachments/assets/0d70ac3a-d7e1-46ae-a08e-8a0863561a5a)

- 조언해주신 대로 Firebase RemoteConfig를 `RemoteConfigPromotionDataSource`가 가져오고 인터페이스 형태를 DefaultProtionRepository가 주입받아 사용하게 구현하였습니다
- 로컬에 오늘 다시 보지 않기 기능을 구현하기 위해 `PromotionDataStore`를 구현하였으며 DataStore에 이미 Local의 이미가 있다고 생각하여 따로 패키지분리나 이름에 Local를 넣지는 않았습니다.
- 최종 로직은 `오늘보지않기를 하지 않았는가? && 프로모션 기간이 유효한가?`를 판단하여 다이얼로그를 보여줍니다.
- 다이얼로그 이미지가 제대로 불려오지 않는다면 다이얼로그를 종료합니다.

### `RemoteConfigPromotionDataSource` 코드설명
```
{
  "imageUrl": "~~",
  "detailUrl": "~~~",
  "endDate": "2024-12-07",
  "startDate": "2024-12-02"
}
```
- 위의  값은 RemoteConfig에서 내려주는 값의 JSON 형태입니다.

```
init {
            remoteConfig.setDefaultsAsync(DEFAULTS)
        }

companion object {
            val DEFAULTS =
                mapOf(
                    "promotionPopup" to """{"imageUrl":"","detailUrl":"","startDate":"","endDate":""}""",
                )
        }
```
- RemoteConfig 가이드라인에서 본인들이 서버가 연결되지 않았을 때 어떤 Default값을 설정하는 것을 강력하게 권장하고 있습니다. 그래서 기본값을 부여하는 코드가 존재합니다.

` private fun calculatePromotionActive`
- 이벤트 프로모션 활성화 날짜와 오늘 날짜를 비교하여 Promotion이 유효한지 판단을 합니다.` 시작날짜 ~ 끝나는날짜`에 오늘 날짜가 포함되는지 판단합니다.

`suspend fun fetchPromotionData`
- `Firebase.remoteConfig`를 통해서 `JSONObject`를 가져와 데이터를 `Promotion`을 만들어 결과를 반환합니다.

### `PromotionDataStore` 코드 설명
- DataStore<Preferences>를 사용하여 값들을 관라합니다.

`isPromotionDismissed 변수` 
- `Flow<Boolean>` 자료형으로 사용자가 프로모션을 `보지 않기`를 선택했는지 날짜를 보고 여부를 판단하는 변수입니다.
- 오늘 날짜가 사용자가 이전에 선택한 `보지 않기`기간에 들어온다면 false를 반환합니다.

`DataStore에 StartDate, EndDate를 저장하는 이유`
- 지금은 `오늘 보지 않기` 기능이지만 추후에 `1주일 동안 보지 않기`, `3일 동안 보지 않기` 등으로 기능이 변경될 수 있는 확장성을 고려하여 시작날짜와 종료날짜를 저장합니다.
- 현재는 `오늘 보지 않기` 기능이기 때문에 `StartDate == EndDate`로직입니다.

## SCREENSHOT (Optional)
- 이미지 클릭시 외부링크 이동
https://github.com/user-attachments/assets/90f96752-a063-4ebf-b751-be64bbaf6326

- 종료 기능 구현
https://github.com/user-attachments/assets/68ee424a-cff0-4158-9a7a-4001a9cc6855

2024-12-06 11:54 UTC, no1msh requested changes
고생하셨습니다!
코멘트 남겼으니 확인해주세요~

또한 오늘 안보기 기능은 오늘 자정 이후 잘 보이는지 테스트도 부탁드립니다.

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +        }
`return runCatching`을 사용하면 Result타입으로 반환할 수 있습니다.

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +        }
되도록이면 문자열 상수화를 해주세요!

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +        }
중간에 JSON 형식의 String을 `Promotion` 객체로 변환하는 로직이 있는데,
Kotlin Serialization을 사용해서도 구현할 수 있습니다. [참고](https://tourspace.tistory.com/367)

현재도 작동이 잘된다면 굳이 바꿀 필요는 없지만, 일단은 프로젝트가 `Kotlin Serialization`를 사용하는 만큼 알아두셨음 해서 남겨봅니다!

2024-12-06 11:54 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/home/component/PromotionDialog.kt
> +}
커밋 전에 TODO가 남아있다면 warning이 뜰텐데, 한번 확인하시고 지워주세요~

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +    }
문자열 상수화 해주세요~

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +                }
무엇을 걱정해서 try-catch 구문을 사용하게 되셨나요?

2024-12-06 11:54 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeViewModel.kt
> +        }
runCatching 하는 부분을 repository 구현체에서 하게 해주고 함수 반환을 Result 객체로 받아오면 좀더 깔끔한 뷰모델 코드가 될 수 있을 것 같습니다!

2024-12-06 11:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
`PromotionDataStore`에서도 똑같은 함수가 있던데,
다음과 같이 유틸함수로 빼도 좋을 것 같네요.

`fun isTodayWithin(startDate: LocalDate, endDate: LocalDate): Boolean`

2024-12-06 14:48 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +        }
`runCatching`을 이용하여 반환하겠습니다 
`Serialization`을 생각 못했었네요 최대한 리펙토링해보겠습니다 좋은 리뷰 감사합니다.

2024-12-06 14:48 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/home/component/PromotionDialog.kt
> +}
일부러 남겨두긴 했는데 일관성 있게 제거하겠습니다

2024-12-06 14:48 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +    }
확인하였습니다!

2024-12-06 14:50 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +                }
DataStore에서 StratDate, EndDate String을 불러와 `String`에서 `LocalDate` 변환하는 과정이 있기 때문에 혹시나 잘못된 형태에 String 때문에 변환이 실패할 것을 우려하였습니다.

2024-12-06 14:52 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
저도 구현하면서 같은 로직이라고 파악은 하였는데 유틸로 뺄 생각은하지 못하였네요. 똑같은 로직이 다른 곳에 또 추가되어 3번 정도 같은 로직이 반복된다면 유틸함수로 빼보겠습니다

2024-12-06 14:53 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeViewModel.kt
> +        }
확인하였습니다.

2024-12-06 14:54 UTC, librarywon commented
좋은 리뷰 감사합니다. 테스트 기기의 설정 날짜를 바꿔가며 `오늘 그만 보기` 기능이 정상작동하는 것을 확인하였습니다.
리뷰주신내용 빠르게 반영하도록 노력하겠습니다

2024-12-07 01:54 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +                }
String 에서 LocalDate 변환하는 과정에서 변환에 실패하는 케이스는 다음과 같습니다.

- 애초에 DataStore에 잘못된 Date들을 저장
- 맞게 저장했으나 formatter를 잘못 지정

모두 개발자휴먼에러에 가까운 잘못된 케이스에 가깝고, 예외 발생 가능한 케이스가 위처럼 두 가지 밖에 안되기 때문에, 이 경우에는 빠르게 에러를 발생시켜, QA 단계 안에 잡히는게 더 유리해 보입니다.

2024-12-07 01:57 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
제가 유틸이라고 했지만, 날짜, 시간을 자주쓰는 서비스 특성상 도메인 로직이 될 수도 있을 것 같습니다.
이미 두 번이상 같은 로직을 반복한 순간 그건 함수화가 필요하다는 시그널이 될 수 있습니다.
`||` 와 `&&` 을 여러개 사용하여 가독성이 안좋은 것도 한몫하구요!

2024-12-07 06:49 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datastore/PromotionDataStore.kt
> +                }
말씀해주신 내용 이해하였고 납득이 가는 부분입니다 해당부분 반영하겠습니다

2024-12-07 06:51 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
도메인 로직이 될 수 있다는 말씀 동의합니다 그렇다면 저 함수의 위치는 어디에 있어야한다고 보실까요?

2024-12-08 02:31 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
그건 위에 말했듯, 구현하는 사람 생각하는 대로 하셔도 될 것 같습니다. ㅋㅋㅋㅋ

만약 유틸로 했다면, 추후 비슷해 보이는 도메인 로직이 생긴다면 합병하여 새로운 도메인 로직으로 남을 수 있을 것 같습니다.

2024-12-08 02:39 UTC, no1msh requested changes
함수화쪽 코멘트랑 디펜던시 쪽 코멘트만 다시 확인해주세요!

2024-12-08 02:39 UTC, no1msh commented on main-data/build.gradle.kts
> +    implementation(libs.kotlinx.serialization.json)
`retrofit.kotlin.serialization`
이친구 없이 잘 돌아가지 않나요?

2024-12-08 04:36 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/datasource/RemoteConfigPromotionDataSource.kt
> +                )
유틸에 도메인 로직을 넣는걸 망설였었는데 좋은 답변 감사합니다

2024-12-08 04:38 UTC, librarywon commented on main-data/build.gradle.kts
> +    implementation(libs.kotlinx.serialization.json)
이것만 추가 했을 때 안되고 아래를 추가해서 Json이 돌아갔던거라 제거하고 실행해보겠습니다

2024-12-08 10:36 UTC, librarywon commented on main-data/build.gradle.kts
> +    implementation(libs.kotlinx.serialization.json)
`implementation(libs.kotlinx.serialization.json)` 만으로 잘 돌아가는 것을 확인하였고 제거하겠습니다!

2024-12-08 11:43 UTC, no1msh approved these changes
리뷰 반영하시느라 고생많으셨습니다!

2024-12-08 11:55 UTC, merged