타이머관련 리팩토링 및 최근앱에서 제거 해도 다시 반영되게 변경
Woosopt/HongikYeolgong2-Android pull request #156
Opened 2024-12-11 06:45 UTC by no1msh

resolved #137 
resolved #138

## AS-IS
- 타이머에서 뷰로직포함
- 홈뷰모델에서 타이머관련 로직 포함
- 최근앱에서 제거하면 서비스는 돌아도 뷰는 복구되지 않았음

## TO-BE
- 타이머에서 뷰로직 제거
- 홈뷰모델에서 타이머관련 로직 제거
- 최근 앱에서 제거해도 뷰 복구 되게 변경

## KEY-POINT
- 홈에서 각종 다이얼로그들이 떠있는지에 대한 상태까지 UIState로 다루는 것을 분리하였습니다.
- 프로모션 다이얼로그는 프로모션에 대한 데이터에 따라 다이얼로그를 표시할지 말지를 정함으로 뷰모델에서 관리하는게 맞지만, 다른 다이얼로그들은 HomeScreen 딴에서 자체적으로 처리가 가능하다 판단하여 분리하였습니다.
- 상태 호이스팅은 필요한 곳 까지만 올리는 것이 유리합니다.

- QA용 앱은 메일로 보내드렸습니다 :)

2024-12-11 17:58 UTC, librarywon requested changes
힘들고 험난한 작업 진행해주셔서 너무 감사합니다. 보내주신 apk 테스트를 진행 해보았고 궁금한점이나 코멘트를 남겼으니 확인해주시면 감사드리겠습니다!

2024-12-11 17:58 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/home/model/HomeUiState.kt
>      ) : HomeUiState
확실히 프로모션을 제외하면 다른 다이얼로그를 UiState에서 관리하는게 update 보일러플레이트 함수도 늘어나고 불필요하다고 느꼈었는데 이번에 반영해주셨군요 감사합니다

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/Time.kt
> +            val meridiem: Meridiem = if (localDateTime.hour >= HIGH_NOON) Meridiem.PM else Meridiem.AM
`HIGH_NOON`이라는 기준이 있군요 이번에 처음 알았습니다

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/Time.kt
> +data class Time(
`Time`이라는 이름은 너무 일반적이고 추상적인 느낌이 강한 것 같습니다. 더 목적을 분명하게 `TimerTime`으로 변경하는 것은 어떠실까요?

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/Time.kt
> +        get() = "$hour:$minute"
`hourAndMinute` 변수도 `formattedTimerTime`이라고 변경하는 것은 어떠할까요?

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/model/LeftTime.kt
> +                val timeOver = String.format(Locale.KOREA, LEFT_TIME_FORMAT, 0, 0, 0)
이 timeOver 값 자체도 상수화 가능해 보입니다

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerViewModel.kt
> +            val startTime = LocalDateTime.now()
자료형 명시하면 좋을 것 같습니다.

2024-12-11 17:58 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/home/HomeViewModel.kt
> +                                Log.d("bandal", "loadPromotionData: isDismissed = $isDismissed promotion = $promotion")
혹시 로그들은 제거 예정이신가요?

2024-12-11 17:58 UTC, librarywon commented on timer-data/src/main/java/com/teamhy2/hongikyeolgong2/timer/data/datastore/TimerDataStoreDataSource.kt
> +    ) : TimerDataSource {
DataStore로 관리하는 방법을 선택하셨군요 코드들도 이해가 전부 이해가 잘 됩니다 👍

2024-12-11 17:58 UTC, librarywon commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
>                  val leftSeconds: Long = leftTime.seconds
```
val leftSeconds: Long = leftTime.seconds
while(leftSeconds > Duration.ZERO){
}
```

이렇게 아래 로직과 통합하시는건 어떤가요?

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                intent.getLongExtra(EXTRA_END_TIME, System.currentTimeMillis() + 1000 * 60 * 60 * 4)
`1000 * 60 * 60 * 4` 상수 자체는 난해한 감이 있는 것 같습니다. 적절한 상수화가 필요해 보입니다

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                        val leftTime =
자료형 명시 부탁드립니다!

2024-12-11 17:58 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                withTimeout(4000L) {
`withTimeout(4000L)`에서 4초를 기준으로 잡으신 이유가 뭔가요?

2024-12-12 01:14 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                withTimeout(4000L) {
runBlocking을 사용한 이유부터 말씀드리자면, 서비스가 stop될 때, 공부시간을 저장하는 로직이 완료되지 않은 상태에서 종료되는걸 경계해서 사용하였습니다. (물론 서비스 스코프에서도 잘 돌아가기는 합니다. 혹시모를 상황을 대비하여 사용하였습니다.)

스레드를 블로킹함으로 ANR(5초동안 메인스레드 블락)의 위험성이 있기에 아무리 블로킹을 오래 하더라도 4초를 못넘기게 한 것입니다.

2024-12-12 01:38 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
>                  val leftSeconds: Long = leftTime.seconds
함수 사용처가 여기뿐이라 `isNotTimeOver`로 변경하였습니다.

2024-12-12 10:16 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/presentation/TimerForegroundService.kt
> +                withTimeout(4000L) {
ANR을 염두하고 한 것이 맞았군요 답변 감사합니다.

2024-12-12 10:20 UTC, librarywon approved these changes
리뷰 반영 고생하셨습니다 다시 꼼꼼히 봤는데 정말 수고많으셨습니다!

2024-12-12 10:25 UTC, merged