[Feature] HY2Dialog 공통 컴포넌트를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #16
Opened 2024-07-17 18:32 UTC by librarywon

resolved #9 

## AS-IS
재사용 가능성이 높아보이는 버튼이 두개 있는 다이얼로그를  

## TO-BE
디자인 시스템에 구현합니다.

## KEY-POINT
- 버튼 로직이 공통되는 부분이 많아 `HY2DialogButton`를 파일 분리하지 않고 내부에 정의하여 코드 가독성을 높혔습니다.
- 다이얼로그에만 사용되는 버튼이기 때문에 파일로 따로 분리하지 않았습니다.
- 상수화는 사이즈 관련 요소들만 하였습니다.
- `LocalConfiguration.current.screenWidthDp.dp`라는 신통방통한 놈을 사용해서 width값을 조정하였습니다.
- 보다 범용성 있는 다이얼로그 사용을 위해 button의 이름을 left와 right로 명명하였습니다. 오른쪽 버튼이 항상 enable or active 버튼이 아니기 때문입니다.
- button, text, background 색상은 기본값을 넣어두고 혹시나 색상이 다른 버전의 사용을 위해 인자로 열어두었습니다.
- back button을 눌렀을 때 dismiss 되는 속성은 true를 해두었고 밖을 누르는 것은 false를 해두었습니다.

## SCREENSHOT (Optional)
임시로 메인 엑티비티로 테스트 해보았습니다 (코드에는 테스트 코드가 없습니다)

https://github.com/user-attachments/assets/327f45ec-0b02-45b5-b515-a44a45ef771f

2024-07-18 06:11 UTC, no1msh requested changes
고생하셨습니다!
몇 가지 코멘트 남겨드렸으니 확인해주세요!

2024-07-18 06:11 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +}
만들어둔 공통 컴포넌트 버튼을 사용하는건 어떨까요?

공통 컴포넌트 그대로 사용해도 좋고, 아니면 이렇게 함수로 분리하되 안쪽은 그냥 `Button`이 아닌 공통컴포넌트 버튼을 사용해도 될 것 같네요!

장단점 비교해보시고 코멘트 달아주세요.

2024-07-18 06:11 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +private val DIALOG_CORNER_RADIUS = RoundedCornerShape(8.dp)
단잠때 상수화 관련 이야기를 했던 기억이 납니다!
다시 한번 확인해주세요.

2024-07-18 06:11 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +            ) {
`Column` 만 사용하는 것과 `Surface` 안에 `Column`을 사용하는 것의 차이는 무엇일까요?

2024-07-18 06:11 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +fun HY2Dialog(
**피그마 디자인 상 다이얼로그가 보일 시 여백의 Dim 처리율은 75%** 입니다.
지금 컴포저블 함수는 따로 처리해주는 곳이 없어보이네요!

2024-07-18 06:11 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +                    )
버튼 클릭시 리플효과가 없는데, 의도된건지 궁금합니다!

2024-07-18 07:12 UTC, librarywon reviewed
리뷰 감사합니다 반영하겠습니다! 코멘트도 확인해주세요

2024-07-18 07:12 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +private val DIALOG_CORNER_RADIUS = RoundedCornerShape(8.dp)
반영하겠습니다.

2024-07-18 07:12 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +fun HY2Dialog(
기본으로 제공해주는 것을 사용하려고 했었는데 디테일을 챙기지 못하였네요!

2024-07-18 07:12 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +            ) {
Column만 사용하는 경우 디자이너가 제시하는 conner radius를 적용하지 못하였습니다.
또한 추후 디자인의 변경이 생겨서 그림자가 생기거나 추가 디자인적 요소를 변경하는데 `Surface` 안에 구현하는 것이 적합하다고 생각하였습니다.

2024-07-18 07:12 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +}
다이얼로그의 버튼과 공통 컴포넌트 버튼를 비교해 보았을 때

radius 값, 색상, textFont가 다릅니다.

현재 공통 버튼컴포넌트는 `backgroundColor`, `textColor`, `modifier`를 인자로 받을 수 있게 설계되었으며 

textFont를 대응하지는 못하는 상태입니다. 그래서 공통 컴포넌트를 사용하지 않고 새롭게 구현하였습니다.

대응 방법은 2가지가 있는 것 같습니다.
1. 공통 컴포넌트 버튼에 textFont까지 확장가능성을 열어주고 공통 컴포넌트를 사용한다.
2. 기존 방식을 유지한다.

어떻게 생각하실까요?

2024-07-18 07:17 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +                    )
프리뷰에서는 리플효과가 보이는데 시연영상에서는 없는 것으로 보이네요? 확인하겠습니다.

2024-07-18 07:50 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +                    )
확인결과 존재합니다 화질문제 같네요

2024-07-19 12:15 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2Dialog.kt
> +}
아하 얼핏 보기에 비슷해보였지만, 다른 점이 생각보다 많군요. 이대로 유지해도 될것 같습니다.

2024-07-19 12:16 UTC, no1msh approved these changes
고생하셨습니다!

2024-07-19 15:13 UTC, merged