[Feature] SettingScreen을 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #20
Opened 2024-07-26 16:13 UTC by librarywon

resolved #18 

## AS-IS
공지사항, 알림 설정 관리, 회원 탈퇴 관리를 할 수 있는 SettingScreen을 

## TO-BE
구현합니다.

## KEY-POINT
고민 했던 점

1. Setting에 도메인이 필요할까?
- 아무리 봐도 SettingScreen에는 도메인 로직이 보이지 않았습니다. 저희가 클린아키텍처 구조를 따르기로 하였고 그 구조에 맞게 개발한다면 dataSource에 저장하고 있는 `열람실 종료 시간 알림 ON/OFF`를 `가져오는 UseCase`, `수정하는 UseCase`, 그저 상하차 UseCase가 만들어진다고 생각하여 
- setting-presentation이 setting-data를 직접 참조하는 로직으로 구현하였습니다.

2. Screen단에서 HiltViewModel을 생성하니 프리뷰가 안보이네?
- 뷰모델이 Screen 생성자에 바로 주입되면 프리뷰에서 확인이 바로 불가능한 현상을  확인하였습니다 ( 당연한건데 다 만들고 깨달았네요)
- 그래서 이 부분에 대해서 알아보니 `Jetpack Compose 에서 절대로 해서는 안되는 20가지 실수`라는 글의 내용에 해당하는 실수였고 여기서 제안하는 해결방법으로 Screen을 구현해 보았습니다. 참고 블로그 링크는 아래 첨부 드리겠습니다.
<img width="604" alt="스크린샷 2024-07-27 오전 1 04 12" src="https://github.com/user-attachments/assets/74e1b76f-2b16-431a-b0f6-d0add19224af">
<img width="613" alt="스크린샷 2024-07-27 오전 1 04 21" src="https://github.com/user-attachments/assets/c3f6d927-acfc-4c64-be9c-fc84ae10a312">

https://velog.io/@mraz3068/Jetpack-Compose-Top-20-mistakes-6-10

3. navController 배치
- 아직 navController를 제대로 써보지 않았지만 참고 싱글 엑티비티에서 스크린이 전환되는 방식에서 navController를 인자로 받아 관련 로직을 처리하는 것이 필요하다고 생각하여 배치하였고 아직 주석을 처리해둔 상태입니다.

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/161f99ec-78bf-4c5a-9895-dcfe0f0884ab

2024-07-27 11:04 UTC, no1msh requested changes
이번에 리뷰사항이 조금 많았습니다!
아무래도 같이 코딩을 한지 얼마 되지 않았다보니 얼라인 하는 과정의 고된 요소라고 생각합니다.
제 의견 무조건 맞는 것은 아니니 천천히 읽어보시고,  코멘트 또는 DM으로 의견을 나누는건 언제든 환영입니다!

고생많으셨습니다!

2024-07-27 11:04 UTC, no1msh commented on setting-data/build.gradle.kts
> +}
빈 블록은 지워줘도 좋을 것 같습니다!

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +}
`Root`가 아닌 통상적으로 사용되는 `Route`라는 네이밍을 사용하는 건 어떨까요?
ex. `SettingsRoute` 그 안에서 호출하는 컴포저블은 `SettingsScreen`

또한
`SettingsScreen`은 최대한 Preview를 통한 테스트 할 수 있게 만드는 것이 좋아보입니다.
그렇게 하려면 최대한 `UiState` 또는 Primitive, String 객체 위주로 넘겨주는 것이 유리합니다.

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +    )
`navController`를 넘겨주지 않고 화면이동을 하려면 어떻게 해야할까요?

droidknights 앱 또는 danjam 앱 등에서 참고해보시면 좋을 것 같습니다.

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +    val state by viewModel.state.collectAsState()
뷰모델을 함수안에 지역변수로 주입 시켜주는 이유는 Preview 때문인가요? 
Route를 Preview를 작성해주기보다 Screen을 Preview를 작성해주는게 편할겁니다.

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingViewModel.kt
> +        }
Event를 다루는건 어느 레포에서 참고하셨나요??
저는 평소에 이렇게 다루지 않아 한번 확인해보고 싶습니다.

2024-07-27 11:04 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +    }
Repository와 DataSource의 차이는 무엇일까요?

또한 Interface로 추상화 하지 않는다면 어떤 고생을 할까요?
ex. 지금은 파이어베이스 혹은 로컬에 저장하지만 aws 서버를 사용하게 된다면?

2024-07-27 11:04 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +        }
공동 객체에 전부 정의해준 이유는 무엇일까요?

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingButton.kt
> +private const val ARROW_SIZE = 24
철저한 상수화 굿입니다. bb

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingButton.kt
> +                contentDescription = "$text 로 이동합니다.",
string resource여도 자바의 `printf`처럼 포멧팅 기능을 사용할 수 있습니다.
xml 시절엔 그렇게 자주 사용했었는데 Compose에선 잘 모르겠지만 한번 찾아봐 주세요!

지금은 localization 대응을 전혀 하지 못합니다.
쉽게 말해 영문으로 바꿔야한다면 아에 해당 코드를 변경해줘야합니다.

2024-07-27 11:04 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingButton.kt
> +    ) {
여기에 있는 인자들 전부 Row에서 다 적용이 가능할 거 같은데, Row만 두는건 불가한가요?

2024-07-29 12:59 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingButton.kt
> +    ) {
시도해 보았는데 정확히 다 적용 가능합니다!! 컴포넌트의 뎁스를 줄여주셔서 감사합니다 ㅎㅎ

2024-07-29 13:03 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingButton.kt
> +                contentDescription = "$text 로 이동합니다.",
`<string name="navigate_to">%1$s 로 이동합니다.</string>`

이렇게 사용할 수 있고 %1은 첫 번째 인수를 의미합니다. %N으로 여러 인수를 받아와 사용이 가능하겠군요 ㅎㅎ

2024-07-29 13:21 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingViewModel.kt
> +        }
제가 첨부드린 링크의 방법을 참고하였습니다! 아마 필립레크너씨 유튜브에 관련 영상도 있을 듯 한데 확인 후 알려드리겠습니다!

2024-07-29 13:32 UTC, librarywon commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +    }
Repository는 저장소 그 자체라고 생각하고 여러 DataSource로부터 데이터를 수집하거나 조합하는 역할을 합니다.
DataSource는 직접 상호작용을 하는 친구이구요 말씀대로 Interface로 추상화 하지 않는다면 예시 상황처럼 변경이 생길 때 막대한 양의 코드를 뜯어 고치는 상황이 발생할 것 같습니다.

저희 앱 구조에서는 presentation에서 domain useCase를 통해 domain Repository의 함수를 호출하고

domain Repository가 실제로 구현체가 있는 data RepositoryImp를 통해서 데이터를 얻어오는 구조를 작성하면 될 것 같은데 

괜찮을까요?

2024-07-29 13:44 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +}
```
@Composable
fun SettingRoute()
```

처럼  통상적으로 사용하는 이름으로 변경해보겠습니다.

그리고 UiState 또는 Primitive, String 객체 위주로 넘겨주는 방식을 단잠과 드로이드나이트 레포를 참고 하였는데 적용 해볼 예정입니다.

2024-07-29 13:46 UTC, librarywon commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +        }
상수화를 위해서 작성을 하였습니다!

2024-08-05 14:40 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +    }
DataSource는 결국에 데이터를 가져오는 곳이 로컬이냐 서버냐 아니면 다른 어디냐와 상관없기 위해 한 단계 추상화를 거치기 위하여 사용을 합니다.

> 저희 앱 구조에서는 presentation에서 domain useCase를 통해 domain Repository의 함수를 호출하고
domain Repository가 실제로 구현체가 있는 data RepositoryImp를 통해서 데이터를 얻어오는 구조

네 이게 보통은 맞긴 한데, 일명 쓸모없는 유즈케이스라고 그저 도메인 레포지토리의 함수를 래핑한 Usecase는 지양하라는 말도 있습니다. 
도메인 레포지토리를 presentation 레이어에서 곧바로 참조해서 사용해도 좋을 것 같네요.
만일 여러 레포지토리들의 함수를 섞어서 하나의 결과물을 만들어야한다면? 그땐 유즈케이스 사용이 좋아보입니다.

2024-08-05 14:41 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +        }
함수들은 공동객체에 위치한 이유가 무엇인가요?

2024-08-06 14:23 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +    val state by viewModel.state.collectAsState()
넵 반영하겠습니다.

2024-08-06 14:23 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/SettingScreen.kt
> +    )
```
@Composable
fun SettingsRoute(
    onNavigateBack: () -> Unit,
    onNoticeClick: () -> Unit,
    onInquiryClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val viewModel: SettingsViewModel = hiltViewModel()
    val state by viewModel.state.collectAsState()

    SettingsScreen(
        state = state,
        onEvent = viewModel::onEvent,
        onNavigateBack = onNavigateBack,
        onNoticeClick = onNoticeClick,
        onInquiryClick = onInquiryClick,
        modifier = modifier,
    )
}
```

이런식으로 Route에서도 이동 이벤트를 호이스팅 시키고 외부 네비게이션이 이동시켜주는 로직으로 해보겠습니다!

2024-08-07 08:02 UTC, librarywon commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +    }
도메인 레포지토리의 함수를 래핑한 Usecase는 지양하는 것에 동의하고 이전에 Usecase의 개념을 혼동하기도 했던 것 같습니다 레포지토리를 바로 참조하는 방향으로 결정하겠습니다.

2024-08-07 12:04 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +        }
![image](https://github.com/user-attachments/assets/cbfad7f5-8103-40e9-889d-eadfd6a7497d)

2024-08-07 12:04 UTC, no1msh commented on setting-data/src/main/java/com/teamhy2/feature/setting/data/datasource/SettingsDataSource.kt
> +        }
Kotlin 공식문서에 맞춰 `companion object`를 이동해주세요!

2024-08-07 14:49 UTC, merged