[Feature] Timer 컴포넌트를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #22
Opened 2024-07-28 15:09 UTC by librarywon

resolved #21 

## AS-IS
Home 화면에 사용되는 Timer 컴포넌트를 

## TO-BE
구현합니다.

## KEY-POINT
- kotilnx를 사용하기 위해 kotiln.library에 CoroutineKotlin 추가하였습니다.
- 30분, 5분 0분 관련 로직을 도메인에 옮겨둘려고 노력해보았는데 아직 방법을 잘 모르겠습니다.
- 정말 부족함을 많이 느끼는 컴포넌트였습니다.
- 피드백 강하게 주시면 더 자세히 공부하겠습니다!

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/892ff46b-ab63-44e8-991a-79c82c161c6e

2024-07-29 07:38 UTC, no1msh requested changes
어려운 피쳐 고생많으셨습니다!
몇 가지 코멘트 남겨 드렸으니 확인부탁드립니다.

복잡하고 어렵다면 조금은 나누면서 `분할정복`하는 것이 생각 정리에도 도움됩니다!
화이팅입니다!

2024-07-29 07:38 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/usecase/TimerUseCase.kt
> +    val formattedRemainingTime: String
이 객체 안에 있는 로직들이 `Timer` 안에 있지 않은 이유가 있을까요?

`Usecase` 에대한 내용은 한번 다시 [공식문서](https://developer.android.com/topic/architecture/domain-layer?hl=ko)를 확인해보는 것도 이해에 도움이 될 거 같습니다.

2024-07-29 07:38 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
> +class Timer(
상수화 할 수 있는 값들이 많이 보입니다!

2024-07-29 07:38 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/usecase/TimerUseCase.kt
> +        }
flow를 활용하신점 좋군요!
다만 함수 네이밍이 잘못되어 보입니다.

2024-07-29 07:38 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/TimerViewModel.kt
> +        private set
`StateFlow`와 비교하였을 때 `MutableState`를 사용하신 이유가 있나요?

2024-07-29 07:38 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +
개인적인 생각으론 깃허브에서 코드를 봐도 이해가 잘되는 코드, 즉 가독성이 좋은 코드가 좋은 코드라고 생각합니다.

**현재 코드는 리턴 타입이 뭐가될지 보는 사람의 입장에서 유추를 해야합니다.**

이펙티브 코틀린이 있으시다면 다음 내용 들을 참고해보시고 없으시다면 블로그 포스팅 봐보시는걸 추천드립니다!
-  Item 4 : Inferred Type으로 리턴하지 말라
- Item 14 : 변수 타입이 명확하지 않은 경우 확실하게 지정하라

[관련 포스팅](https://velog.io/@no1msh1217/Kotlin-Inffered-Type%EC%9D%84-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-07-29 07:38 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +) {
해당 컴포저블 함수도 부위별로 나눌 수 있을 것 같습니다!

2024-07-30 08:20 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +) {
start ,end 부분보가 TimeLeft 부분을 나누는 것을 생각하면 될까요? 부위별로 어떻게 나눌지 생각이 잘 안나는 상태입니다.

2024-07-30 08:30 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +
네 다른 프로젝트에서도 받았던 코드리뷰인데 이번 기회에 더 크게 인지한 것 같습니다 
관련 포스팅 블로그 저자가 아주 쉽게 설명을 해주시는군요 ㅎㅎ

2024-07-30 08:31 UTC, librarywon commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
> +class Timer(
확인하였습니다.

2024-07-30 13:17 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/TimerViewModel.kt
> +        private set
관성적으로 아직 익숙하지 않은 `StateFlow` 보다 `MutableState`를 사용한게 컷던 것 같습니다.

2024-07-30 13:19 UTC, librarywon commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/usecase/TimerUseCase.kt
> +        }
이것에 대해서 고민을 많이 해보았는데 
tick()을 통해 1초를 줄여주는 역할

```
 if (events.containsKey(leftSeconds)) {
                events[leftSeconds]?.invoke()
            }
```
를 통해서 시간을 체크하는 역할을 포함하는 네이밍을 정하기가 어렵네요..

2024-07-30 13:33 UTC, librarywon commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/TimerViewModel.kt
> +        private set
공부를 해보니 `StateFlow`는 코루틴과 잘 통합되고 다양한 CoroutineScope 내에서 상태를 관찰하고 처리할 수 있다라는 사실 알아내었습니다.

비동기 작업을하는 timer 특성상 `StateFlow` 적합하다고 판단하여 StateFlow로 작업을 진행하겠습니다.

2024-07-30 13:49 UTC, librarywon commented
페어프로그래밍으로 진행했던 Timer를 리펙토링하였습니다 눈여겨보실 포인트를 정리해드리자면

1. 분단위 이벤트 기준을 초단위로 변경하였습니다.
- 분단위로 진행시 30:01~30:59 동안 계속 이벤트가 발생하는 것을 파악하였습니다.

2. 헷갈리는 remaining time이란 단어를 화면상에 나타나는 left time으로 모두 변경하였습니다.

나머지 부분은 같이 페어를 하면서 지적해주시거나 의견을 나누어주신 것을 반영하였습니다 확인해주시면 감사드리겠습니다.

@no1msh

2024-07-31 14:21 UTC, no1msh approved these changes
고생하셨습니다!
몇 가지 코멘트 남겨드렸으니 확인부탁바랍니다.

2024-07-31 14:21 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
> +        }
아 리뷰할때 다시 보니 지금 구조에선 굳이 팩토리 함수가 필요가 없군요.
함수의 내용을 init 블록으로 옮기면 똑같이 작동할 것 같습니다.

2024-07-31 14:21 UTC, no1msh commented on timer-domain/src/main/java/com/teamhy2/hongikyeolgong2/timer/model/Timer.kt
> +        }
상수화 해주세요~

2024-07-31 14:21 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +        }
이 계산들은 리컴포지션 될 때 같이 무조건 다시 계산되는 것이 계획되었나요?

2024-07-31 14:21 UTC, no1msh commented on timer-presentation/src/main/java/com/teamhy2/hongikyeolgong2/timer/prsentation/Timer.kt
> +) {
네네 말씀하신대로 분리하면 좋을 것 같습니다.

2024-08-02 08:01 UTC, librarywon commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +    }
생각해보니 아래 로직과 같은 로직 같기도 하네요

2024-08-02 08:02 UTC, librarywon commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +    }
지금 보니 위 테스트와 같은 로직을 테스트하고 있네요

2024-08-05 14:35 UTC, no1msh approved these changes
고생하셨습니다!
피드백 몇개 남겨드렸으니 반영하실 거 하시고 머지하셔도 좋을 것 같습니다.

2024-08-05 14:35 UTC, no1msh commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +            }
현재 검증부는 `2 + 1 should be 2 + 1` 이나 다름없습니다.
should be 다음에 올 expect는 3 이런식으로 만들어주세요!

2024-08-05 14:35 UTC, no1msh commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +    }
1초가 지나는 로직은 따로 없나요?

runTest 블록 안쪽 부분에 대해 설명해주세요!

2024-08-06 14:26 UTC, librarywon commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +            }
아 정확하게 이해하였습니다 ㅋㅋㅋㅋ 잘못 생각했네요

2024-08-06 14:56 UTC, librarywon commented on timer-domain/src/test/java/com/hongikyeolgong2/timer/model/TimerTest.kt
> +    }
`emitTimerEvents()`를 실행하면 내부 tick() 함수를 통해서 1초가 지나는 로직이 발생합니다.

runTest 블록 안에서  `emitTimerEvents()`를 1회 실행한다면 

 `duration = Duration.ofSeconds(10)` 으로 설정되어있기 때문에 10초가 9초로 줄어드는 결과가 발생해야합니다.
 
 그래서 `firstTick shouldBe 9L` 이라는 코드를 작성하였습니다.

2024-08-07 12:41 UTC, merged