[Feature] HY2WebView 공통 컴포넌트를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #26
Opened 2024-08-08 07:01 UTC by librarywon

resolved #24

## AS-IS
공지, 문의사항, 좌석 기능은 같은 형식의 웹뷰와 버튼을 가지고 있습니다.
공통 HY2WebView를 제작하여

## TO-BE
코드 재사용성을 증가시킵니다.

## KEY-POINT
- 다크모드에 대한 대응이 들어가 있습니다.
- WebView에  `settings.javaScriptEnabled = true` 속성을 활성화 시켜야 내부의 버튼을 클릭하는 JS 기능을 활용가능한데 이 속성을 활성화 시키면 프리뷰가 보이지 않는 현상이 있습니다. 

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/914d241e-7586-41a6-9633-a8e488156ee3

2024-08-09 11:43 UTC, no1msh requested changes
고생하셨습니다!
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다!

2024-08-09 11:43 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +        )
클릭시 표시되는 리플 효과에서 알 수 있듯이 매우 터치 영역이 좁아 보입니다!
**최소 Width와 Height를 40dp은 넘겨주세요.**

2024-08-09 11:43 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +    ) {
여기서는 지역변수로 빼두지 않고 바로 `isSystemInDarkTheme()`을 사용하네요!
현재 함수에선 파라미터로 받는 것도 방법이겠네요.

2024-08-09 11:43 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +) {
```kotlin
fun a(){
    b()
}

fun b() {
}
```

함수는 위처럼 큰 범주의 함수가 먼저오고 그 다음에 부속적인 함수들이 들어가는 형태가 가독성이 좋습니다.

2024-08-10 05:09 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +        )
사용성을 고려하지 못했네요 넵 반영하겠습니다!

2024-08-10 05:09 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +) {
HY2WebView를 상단으로 배치하겠습니다!

2024-08-10 05:09 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +    ) {
`HY2WebViewHeader`에서는  `isSystemInDarkTheme()` 활용하는 부분이 2군데 이상이라 지역변수로 빼두고 사용하였고

`HY2WebView`에서는 Column의 Background 색상 변경에만 사용하기 때문에 변수로 따로 빼지 않았습니다. 

`HY2WebView`의 인자로 다크테마 여부를 받는게 어떠냐는 말씀이실까요?

2024-08-10 06:25 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +    ) {
헤더와 바디가 웹뷰 컴포넌트로부터 지금이 다크띰인지 받아오는게 어떨까 한 의견입니다!

2024-08-10 06:48 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +    ) {
아 너무 좋은것 같습니다 반영하겠습니다

2024-08-11 09:12 UTC, librarywon commented
코드리뷰를 완료하였고 아래 내용을 참고해주시면 좋을 것 같습니다.

1. x버튼 터치영역 조절
2. 웹뷰 랜더링 이슈 Box컴포넌트로 감싸서 해결

2024-08-11 15:01 UTC, no1msh approved these changes
고생하셨습니다!

2024-08-11 15:01 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/common/HY2WebView.kt
> +        )
추가로 웬만하면 `IconButton` 컴포넌트를 사용하시는걸 추천드리기도 합니다.
해당 컴포넌트는 알아서 터치 영역에 대한 대응이 되어있습니다!

2024-08-11 15:08 UTC, merged