[Feature] firestore를 통해 url을 받아와 webview를 구성합니다.
Woosopt/HongikYeolgong2-Android pull request #41
Opened 2024-08-20 06:48 UTC by librarywon

resolved #37 

## AS-IS
- 웹뷰에는 해당 url이 필요하고, url을 로컬에 저장하면 추후에 링크가 변경될 때마다 업데이트를 진행해야합니다. 

## TO-BE
- firestore를 통해 remote url을 가져와 링크 변동사항에 대응할 수 있고 웹뷰 이동관련 로직을 완성합니다.

## KEY-POINT
- 웹뷰 스크린은  "좌석배치도, 공지사항, 문의사항" 3개이며, main/webviews 하위에 각각의 패키지를 배치하여 파일을 관리합니다.
- firestore Link 컬렉션의 문서들을 Map<String,String> 형태로 저장하여 뷰에 넘겨주고 이를 활용하여 NavHost가 스크린 이동과 url을 넘겨주는 역할을 수행합니다.
- 캐싱을 하여서 메인 뷰모델이 생성 될 때마다 불러오지 않으면 좋겠지만 이것은 시간이 있다면 진행하고 싶습니다.

## SCREENSHOT (Optional)

https://github.com/user-attachments/assets/c25c9ff1-86ec-4e4d-b4f8-38b833634376

2024-08-20 11:55 UTC, no1msh requested changes
고생하셨습니다!
몇 가지 코멘트 남겨드렸으니 확인부탁드려요!

2024-08-20 11:55 UTC, no1msh commented on main-data/build.gradle.kts
> +}
data 모듈에서는 컴포즈가 없기 때문에 `hongikyeolgong2.android.library`를 사용해야합니다.
다른 모듈도 같이 수정해주세요!

2024-08-20 11:55 UTC, no1msh commented on main-data/src/main/AndroidManifest.xml
> +</manifest>
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<manifest />
```
만약 `xmlns:android="http://schemas.android.com/apk/res/android"`가 회색으로 사용되지 않는다고 표시되면
이렇게 조금이라도 줄일 수 있습니다.

2024-08-20 11:55 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/di/FirebaseModule.kt
> +    }
`@Provides`와 `@Binds`의 차이는 무엇인가요?

2024-08-20 11:55 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/di/FirebaseModule.kt
> +    }
[해당링크](https://developer.android.com/topic/architecture/recommendations?hl=ko&_gl=1*15rybe3*_up*MQ..*_ga*ODQ2MDM4MDMwLjE3MjQxNTQxODI.*_ga_6HH9YJMN9M*MTcyNDE1NDE4Mi4xLjAuMTcyNDE1NDE4Mi4wLjAuMA..#naming-conventions)를 한번 보시구 레포지토리 구현체의 이름을 다시 정해봅시다!

2024-08-20 11:55 UTC, no1msh commented on main-data/src/main/java/com/teamhy2/main/data/repository/FirebaseRepositoryImp.kt
> +}
`FirebaseRepository`라면 이름만 봤을 땐 파이어베이스 스토어를 사용하려면 무조건 이 레포지토리를 사용해야하는 것처럼 보이는데요.

예를들어 `ProductRepository`, `UserRepository` 처럼 나누는 것과 비교했을 때 어떤게 좋을까요?

2024-08-21 06:09 UTC, librarywon commented on main-data/src/main/AndroidManifest.xml
> +</manifest>
아 반달님 PR에서 확인한 내용인데 반영하지 못했었네요 감사합니다!

2024-08-21 06:09 UTC, librarywon commented on main-data/build.gradle.kts
> +}
넵 확인하였습니다!

2024-08-21 06:30 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/di/FirebaseModule.kt
> +    }
`@Provides`는 매서드가 객체를 직접 생성하고 복잡한 초기화 로직이 필요한 경우에 사용
`@Binds`는 이미 생성된 인스턴스를 다른 타입으로 바인딩하는 간단한 바인딩 로직에 사용한다고 알아보았습니다.

지금 제 경우에는 `FirebaseRepository` 인터페이스와 구현체에 바인딩하는 정도의 로직이니 `@Binds`가 적절하다고 생각해서 변경하겠습니다.

2024-08-21 06:31 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/di/FirebaseModule.kt
> +    }
이런 공식문서가 있는줄은 몰랐습니다 감사해요!

2024-08-21 07:54 UTC, librarywon commented on main-data/src/main/java/com/teamhy2/main/data/repository/FirebaseRepositoryImp.kt
> +}
`FirebaseRepository`로 네이밍을 짓는다면 FirebaseFirestore 인스턴스를 사용 하는 곳이 `FirebaseRepository`로 한정되고 FirebaseFirestore 로직관련 응집도가 올라간다고 생각합니다.

그런데 저희 앱을 예시로 들자면 파이어스토어에서 받는 `명언`, `웹뷰url` 등등 서로 다른 도메인이 얽혀서 복잡해지고 유지보수가 어려워질 것 같습니다.

기능별로 레포지토리를  분리해서 레포지토리를 만드는 것이 추후 기능 업데이트 및 유지 보수의 유리할 것 같아 한 번 변경해보겠습니다

2024-08-21 14:29 UTC, no1msh approved these changes
고생하셨습니다!

2024-08-21 21:22 UTC, merged