[Feature] designsystem 모듈을 도입하여 UI 일관성을 높입니다.
Woosopt/HongikYeolgong2-Android pull request #5
Opened 2024-06-29 03:54 UTC by librarywon

solved #2 

## AS-IS
각 팀원들이 개별적으로 스타일과 컴포넌트를 정의하면 중복된 코드와 비효율적인 작업이 발생합니다. 결과적으로, 유지보수가 어렵고 새로운 기능을 추가할 때마다 많은 시간이 소요됩니다.

## TO-BE
디자인 시스템 모듈을 도입함으로써, 모든 팀원이 동일한 컴포넌트와 스타일을 사용하게 되어 UI의 일관성이 높아집니다. 중앙에서 관리되는 시스템을 통해 유지보수가 용이해지고, 새로운 기능 추가 시에도 신속하게 대응 가능합니다.  코드 재사용이 증가하여 개발 효율성의 증가도 기대 가능합니다.

## KEY-POINT
파일추가와 새로운 시스템 도입으로 MR 사이즈가 상당히 큽니다 이 부분을 주의를 하여 다음 PR에는 크기를 준수하겠습니다.

designsystem 모듈 도입 이외의 작업이 존재합니다.
- app 모듈 package 네이밍을 jwseo -> teamhy2로 변경하였습니다.
- app 모듈 내 불필요한 파일을 제거하였습니다. (color, theme, type)
- app 모듈 내에 designsystem이 잘 적용되는지 예시 코드를 넣어두었습니다.

designsystem 모듈 관련
- ColorScheme은 현재 디자이너에게 가이드 받은 것이 없기 때문에 적절한 값을 넣어두었습니다. 해당부분은 디자이너에게 요청을 해볼 생각입니다.
- Type에는 디자이너가 제시해준 이름을 사용할 수 있도록 HY2Typography를 정의하고 구현하였습니다.
- Theme에는 HY2Typography를 적용한 HY2Theme를 구현하고 오브젝트를 생성해 HY2Typography를 접근할 수 있도록하였습니다. 추후 머터리얼 시스템에 알맞은 디자이너 가이드가 나온다면 HY2Color도 제작가능해 보입니다.

디자인 시스템 모듈을 제작할 때 참고한 레퍼런스 링크를 남겨두겠습니다
https://github.com/TeamPophory/pophory-android
https://github.com/sopt-makers/sopt-android
https://github.com/no1msh/Danjam

## SCREENSHOT (Optional)

2024-06-29 06:10 UTC, no1msh requested changes
고생하셨습니다!
몇 가지 코멘트 남겼으니 확인부탁드립니다~~~

2024-06-29 06:10 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Type.kt
> +) {
머티리얼3 기준 Typography가 아닌 독자적인 폰트 시스템을 구축하려면 이렇게 해야하나요?

2024-06-29 06:10 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Type.kt
> +		private set
`mutableStateOf`로 래핑되야 하는 이유는 무엇인가요?

2024-06-29 06:10 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Theme.kt
> +	}
`typography` 지역 변수가 사용하는 쪽에 인라인 되어도 괜찮을거 같은데 혹시 다른 이유가 있을까요?

2024-06-29 06:10 UTC, no1msh commented on build.gradle.kts
> +	alias(libs.plugins.android.library) apply false
`apply false`는 무엇을 의미할까요?

2024-06-29 07:53 UTC, no1msh commented
아 그리고 자동으로 issue closing 시키려면
`resolved #2`로 변경하셔야 할겁니다.
현재는 PR과 issue가 연동되어 있지 않습니다.

2024-06-29 15:33 UTC, librarywon commented on app/src/main/java/com/teamhy2/hongikyeolgong2/MainActivity.kt
> +	)
아 sample 컴포넌트에는 적용하지 않을 것 같습니다 아직 어색하네요!

2024-06-29 15:33 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Color.kt
> +val Yellow100 = Color(0xFFF4F33D)
앗 감사합니다 ㅎㅎ

2024-06-29 15:35 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Type.kt
> +) {
제가 찾아본 결과는 이렇게 구현하는 것이 최선인 것 같습니다! Color system과 같이 구현하는 것이 좋더라구요

2024-06-30 03:47 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Type.kt
> +		private set
스타일이 변경될 때 상태변경을 관찰하고 다시 그릴 수 있도록 `mutableStateOf`를 사용한다고 합니다.

2024-06-30 03:52 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Theme.kt
> +	}
HY2Colors의 추후 추가 가능성을 생각해 보았을 때 가독성 측면에서 좋지 않을까 생각이 들었습니다!

```suggestion
	val typography = HY2Typography()
	val colors = HY2Colors()

	ProvideHY2Typography(typography, colors) {
		MaterialTheme(
			content = content
		)
	}
```

2024-06-30 03:56 UTC, librarywon commented on build.gradle.kts
> +	alias(libs.plugins.android.library) apply false
project단에서 플러그인을 즉시 적용하지 않고 정의할 때 사용한다고 합니다
특정 모듈에서 gradle에서 `apply false` 없이 선언하면 그 모듈만 적용할 수 있다고 확인하였습니다

2024-07-01 12:44 UTC, no1msh commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Theme.kt
> +	}
가독성에 있어서는 취향차이로 보이지만 성능적으로는 근소하게나마 지역변수를 사용하는 쪽이 불리하다고 생각이 듭니다!
`ProvideHY2Typography(HY2Typography(), HY2Colors())` 
이렇게 쓰는 것도 그다지 나빠보이진 않는데 어떤가요?

2024-07-01 12:47 UTC, no1msh approved these changes
고생하셨습니다! 린트도 잘 적용되는 것처럼 보이네요!
댓글에 대댓글 달았으니 한 번 더 확인해보시고 변경하실거면 하시고 아니라면 바로 머지 누르심 될 것 같습니다!

2024-07-01 13:41 UTC, librarywon commented on core/designsystem/src/main/java/com/teamhy2/designsystem/ui/theme/Theme.kt
> +	}
네 좋습니다 반영하겠습니다!

2024-07-01 13:55 UTC, merged