[Feature] 주간 캘린더 컴포넌트를 구현
Woosopt/HongikYeolgong2-Android pull request #96
Opened 2024-10-02 15:17 UTC by librarywon

resolved #91 

## AS-IS
X

## TO-BE
- v2 Home Screen에 존재하는 주간 캘린더를 구현합니다.

## KEY-POINT
- 오늘 기준으로 이후의 텍스트들은 textColor가 다르게 나오도록 설정하였습니다.
- 아래 프리뷰는 10/3일의 기준으로 보이는 UI입니다.
- 프리뷰를 확인하는 개발자가 더 이해하기 쉽도록 프리뷰에 `getThisWeeksDates` 함수를 구현하여 실제 현재 날짜가 연동되서 더 직관적으로 로직을 확인할 수 있도록 구현하였습니다.

## SCREENSHOT (Optional)
<img width="593" alt="스크린샷 2024-10-03 오전 12 12 53" src="https://github.com/user-attachments/assets/06739c47-cc30-4a64-8dc8-726ea4e2cb6e">
<img width="157" alt="스크린샷 2024-10-03 오전 12 13 06" src="https://github.com/user-attachments/assets/fd544d28-258a-4dd7-ae5d-6c0bc853cc96">

2024-10-03 06:47 UTC, no1msh requested changes
고생하셨습니다.
몇 가지 코멘트 남겨드렸으니 궁금하신 점 있거나 의논해볼 거리가 있다면 언제든 대댓 주세요!

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +    val daysOfWeek = DAYS_OF_WEEK
`val daysOfWeek = DAYS_OF_WEEK`

불필요해보이는 지역변수 설정인 것 같습니다.
아니면 다른 이유가 있을까요?

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +            val isFutureDate = isDateInFuture(date, currentDate)
`getOrElse()`를 통해 `""`이 나온다면 어떻게 되나요?

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +) {
아마 `studyCounts`와 `dates`의 개수가 같을거 같은데, 차라리 객체를 만들어 묶어서 사용하면 어떨까요?

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +    val parsedDate = LocalDate.of(currentDate.year, month, day)
타입을 명시해주세요!

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +    val parsedDate = LocalDate.of(currentDate.year, month, day)
추가로 `ChronoField`는 무엇일까요?

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyDayComponent.kt
> +}
서버 구현에 따라 다르겠지만, 만일 공부를 4번해서 studyCount가 4개가 오면 3번 스타가 아닌 0번 공부한 스타로 처리됩니다.

sutdyCount가 0과 양수만 가능하게 하고,
0,1,2,3번 공부한걸 각각 처리하고 else를 4이상으로 처리해서 3번 공부한 스타가 나오게 하는것은 어떨까요?

2024-10-03 06:47 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +}
개발자의 편의성을 위해 정의하신점 너무 좋습니다!

다만 더 개선하려면 특정 날짜의 예시도 볼 수있게, 파라미터로 `LocalDate`를 받고 기본 인자로 `LocalDate.now()`를 정의하는게 어떤지 조언해봅니다!

2024-10-04 05:30 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +    val daysOfWeek = DAYS_OF_WEEK
기존의 요일값을 상수화 하는 과정에서 남은 잔재 같습니다 제거하겠습니다!

2024-10-04 05:32 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +) {
서버에서 저 형태로 내려준다고 말해주어 반영하였는데 데이터를 받아 하나의 객체로 묶어서 넘겨주는 방법도 좋은 것 같습니다 굳이 index를 따지지도 않아도 되구요

2024-10-04 05:33 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyDayComponent.kt
> +}
아 이미 구현했을 때 겪었던 문제였는데 이걸 간과하고 있었네요 말씀해주신 로직을 반영하겠습니다!

2024-10-04 05:33 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +}
오 너무너무 좋은 방법인 것 같습니다 ㅎㅎ 적극 수용하겠습니다!

2024-10-04 05:34 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +            val isFutureDate = isDateInFuture(date, currentDate)
비어있는 날짜로 나오게 될텐데 사용자가 이질감을 느끼지 않도록 그럴듯한 형식을 넣어두어야할까요?

2024-10-04 07:21 UTC, no1msh commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +            val isFutureDate = isDateInFuture(date, currentDate)
완벽하게 대처를 하거나 아니면 빠르게 예외를 터뜨려 디버그 또는 QA 단계에서 찾을 수 있도록 하는게 맞아보입니다!

2024-10-04 09:13 UTC, librarywon commented on main-presentation/src/main/java/com/teamhy2/feature/main/component/WeeklyCalendar.kt
> +    val parsedDate = LocalDate.of(currentDate.year, month, day)
`LocalDate` enum 클레스입니다. 

val parsedMonthDay = formatter.parse(dateText)
val month = parsedMonthDay[ChronoField.MONTH_OF_YEAR]

를 예시를 들면 문자열에서  월을 `LocalDate` 자료형으로 뽑아내는 역할을합니다.

2024-10-04 10:32 UTC, no1msh approved these changes
고생하셨습니다!

2024-10-04 14:42 UTC, merged