[Feature] Setting 스크린의 v1.1.0 UI를 구현합니다.
Woosopt/HongikYeolgong2-Android pull request #97
Opened 2024-10-04 16:27 UTC by librarywon

resolved #93

## AS-IS
X

## TO-BE
- v1.1.0 변경된 디자인에 맞게 Setting 스크린을 수정하였습니다.
- 1.1로 넘어오면서 필요없어진 backButton 로직도 제거하였습니다.

## KEY-POINT
- 바텀네비게이션이 들어올 것을 예상해서 모두 UI 마진이나 디테일을 맞춰두었습니다.

## SCREENSHOT (Optional)
<img width="297" alt="스크린샷 2024-10-05 오전 1 27 31" src="https://github.com/user-attachments/assets/2e7bf1c8-4877-4481-bf6b-28b4d7e981bc">

![Screenshot_20241005_012451](https://github.com/user-attachments/assets/f2fde9bd-677c-4fdc-881b-cb823e0b0e14)

2024-10-05 06:01 UTC, no1msh requested changes
고생하셨습니다.
몇 가지 코멘트 확인해주세요!

2024-10-05 06:01 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingUserProfile.kt
> +        )
다양한 비동기 이미지 라이브러리가 있겠지만, Coil을 활용하여 주세요.

추후 구글 로그인을 통하여 사용자의 이미지를 가져올 때 `URL` 형식으로 가져옵니다.

2024-10-05 06:01 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/model/UserInfo.kt
> +)
`UserInfo` 라는 객체를 만들거면 Presntation에 종속되는 것이 아닌 Domain이 가지는게 어울려 보입니다.

`SettingUiState`에서 `UserInfo`가  필요하시다면 `UserUiState`를 만들어 포함시키는게 맞아보입니다.

또한 default 값을 제공해주셨는데, 이런 경우 휴먼 에러를 발생시켜 정작 데이터를 넣어줘야할 상황에도 default 값이 들어갈 수 있는 상황이 나올 수 있습니다.
컴퓨터공학과는 이 세상의 존재하는 학과중에 기본이 아니니까요!

2024-10-07 07:44 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/components/SettingUserProfile.kt
> +        )
넵 확인하였습니다 아마 이번 피처에서는 사용자의 이미지를 안가져올 것 같긴합니다!

2024-10-07 07:46 UTC, librarywon commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/model/UserInfo.kt
> +)
도메인 모듈을 만들지 않아서 객체를 그냥 뒀던 이유도 있었던 것 같습니다. default 값에 대한 의견도 확인하였고 납득하였습니다

2024-10-21 03:25 UTC, no1msh requested changes
코멘트 확인바랍니다~

2024-10-21 03:25 UTC, no1msh commented on setting-domain/src/main/java/com/teamhy2/feature/setting/domain/repository/model/UserInfo.kt
> +)
default parameter를 지워주세요!

2024-10-21 03:25 UTC, no1msh commented on setting-presentation/src/main/java/com/teamhy2/feature/setting/presentation/model/SettingUiState.kt
>  )
default parameter를 제거해주세요

default는 그대로 값이 들어가도 사용자가 봤을 때 어색하지 않을 것만 해주세요.

UiState를 SealedInterface로 바꾸고 구현하는 Loading을 추가해주세요.
그러면 defaultParameter를 사용하지 않아도 될겁니다!

2024-10-23 06:29 UTC, no1msh approved these changes
고생하셨습니다.
컨플릭트는 제가 처리할게요!

2024-10-23 06:46 UTC, merged